DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS convo;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT UNIQUE NOT NULL
);

CREATE TABLE convo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  conversations TEXT NOT NULL
);